# Generated by Django 4.1.6 on 2023-09-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_rotation_enabled", models.BooleanField(default=False)),
                ("last_rotation_date", models.DateTimeField(blank=True, null=True)),
                ("next_rotation_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
