# Generated by Django 4.1.6 on 2023-09-16 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drf_simple_apikey", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={"verbose_name": "API key", "verbose_name_plural": "API keys"},
        ),
    ]
