# Generated by Django 5.0.3 on 2024-10-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf_simple_apikey", "0003_alter_apikey_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="blacklisted_ips",
            field=models.JSONField(
                blank=True,
                help_text="List of denied IP addresses for this API key.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="whitelisted_ips",
            field=models.JSONField(
                blank=True,
                help_text="List of allowed IP addresses for this API key.",
                null=True,
            ),
        ),
    ]
