# Generated by Django 5.2.17 on 2026-08-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf_simple_apikey", "0003_apikey_blacklisted_ips_apikey_whitelisted_ips"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="scopes",
            field=models.JSONField(
                blank=True,
                help_text=(
                    "List of scopes granted to this API key (e.g. ['read', 'write']). "
                    "Leave empty for unrestricted access."
                ),
                null=True,
            ),
        ),
    ]
