# Generated by Django 5.2.17 on 2026-08-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf_simple_apikey", "0004_apikey_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="hashed_secret",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text=(
                    "SHA-256 hash of a random per-key secret embedded in "
                    "the issued key, checked in addition to Fernet "
                    "decryption succeeding. Only set when "
                    "ENABLE_PER_KEY_SECRET is on. Empty for keys issued "
                    "before this field existed or while the setting is off."
                ),
                max_length=64,
            ),
        ),
    ]
